### ISSUE TITLE
And what helpers are these?

### ISSUE THREAD

**Issue by vjpr** [atom/fs-plus#11]
README should specify these helpers :)

**Comment by IonicaBizau** [comment]
I am on it! :smiley:

**Comment by thomasjo** [comment]
I disagree with this unless we use the same toolchain as for e.g. Atom to autogenerate docs. Otherwise we always need to keep the duplicated documentation in `README.md` in sync with the documentation in [the module](https://github.com/atom/fs-plus/blob/master/src/fs-plus.coffee).

**Comment by IonicaBizau** [comment]
@thomasjo I manually wrote them, in #15. However, I strongly agree that generating the docs is much better.
