### ISSUE TITLE
Read and write JSON methods

### ISSUE THREAD

**Issue by IonicaBizau** [atom/fs-plus#16]
Would it be useful to add methods for reading and writing JSON?

I'm currently using the `read-json` library for that:

```js
var Fs = require("fs-plus");
Fs.readJSON = require("read-json");
```

**Comment by kevinsawicki** [comment]
These used to be in here but were removed in https://github.com/atom/fs-plus/commit/ea0d714b8a4559d350d8a9c570512ec0b2762aec

I'd prefer to keep this library small and only have helpers that build directly on core `fs` APIs.

**Comment by IonicaBizau** [comment]
Thanks! I see. :+1:
