### ISSUE TITLE
crash on calling list

### ISSUE THREAD

**Issue by adrien59cadri** [atom/fs-plus#23]
![image](https://cloud.githubusercontent.com/assets/536398/8907932/6fd325ee-3479-11e5-943a-9ee56e50705d.png)

Here is my code, i have most recent version at this date (27/7/2015)
  "name": "fs-plus",
  "version": "2.8.1",

		var path = fs.normalize(command["path"]);
		console.log(path); // shows d:\github\
		var res = fs.list(path);
		console.log(res);//show undefined
		event.sender.send('command-res',res);

**Comment by kevinsawicki** [comment]
`fs.list` is asynchronous and requires a callback function as the second parameter.

Use `fs.listSync` for the synchronous version.
